import type { RegexExample } from "./types";

export const regexExamples: RegexExample[] = [
  {
    id: "email",
    title: "Email",
    category: "Email",
    pattern: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}",
    flags: "g",
    sampleText: "My email is hello@test.com and backup is admin@example.com",
    description: "Matches common email addresses",
  },
  {
    id: "phone-us",
    title: "US Phone",
    category: "Phone number",
    pattern: "\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}",
    flags: "g",
    sampleText: "Call (555) 123-4567 or 555.987.6543",
  },
  {
    id: "url",
    title: "URL",
    category: "URL",
    pattern: "https?:\\/\\/[\\w.-]+(?:\\/[\\w./?%&=-]*)?",
    flags: "gi",
    sampleText: "Visit https://example.com/path?q=1 and http://test.io",
  },
  {
    id: "date-iso",
    title: "ISO Date",
    category: "Date",
    pattern: "(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})",
    flags: "g",
    sampleText: "Today is 2026-06-22 and tomorrow 2026-06-23",
  },
  {
    id: "time-24",
    title: "24h Time",
    category: "Time",
    pattern: "\\b([01]\\d|2[0-3]):[0-5]\\d\\b",
    flags: "g",
    sampleText: "Meeting at 09:30 and lunch at 13:45",
  },
  {
    id: "integer",
    title: "Integer",
    category: "Number",
    pattern: "-?\\d+",
    flags: "g",
    sampleText: "Values: -42, 0, 100, 3.14",
  },
  {
    id: "letters-only",
    title: "Only Letters",
    category: "Only letters",
    pattern: "^[a-zA-Z]+$",
    flags: "",
    sampleText: "Hello",
  },
  {
    id: "digits-only",
    title: "Only Numbers",
    category: "Only numbers",
    pattern: "^\\d+$",
    flags: "",
    sampleText: "12345",
  },
  {
    id: "password-strong",
    title: "Strong Password",
    category: "Password",
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
    flags: "",
    sampleText: "Abcdef1!",
  },
  {
    id: "hex-color",
    title: "Hex Color",
    category: "Hex color",
    pattern: "#(?:[0-9a-fA-F]{3}){1,2}\\b",
    flags: "g",
    sampleText: "Colors: #fff, #1a2b3c, #ABCDEF",
  },
  {
    id: "ipv4",
    title: "IPv4",
    category: "IP address",
    pattern: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b",
    flags: "g",
    sampleText: "Server 192.168.0.1 and gateway 10.0.0.1",
  },
  {
    id: "username",
    title: "Username",
    category: "Username",
    pattern: "^[a-zA-Z][a-zA-Z0-9_]{2,15}$",
    flags: "",
    sampleText: "user_123",
  },
  {
    id: "whitespace",
    title: "Whitespace",
    category: "Whitespace",
    pattern: "\\s+",
    flags: "g",
    sampleText: "too   many    spaces",
  },
  {
    id: "html-tag",
    title: "HTML Tag",
    category: "HTML tag",
    pattern: "<\\/?[a-zA-Z][^>]*>",
    flags: "g",
    sampleText: "<div class='x'>Hello</div>",
  },
  {
    id: "file-ext",
    title: "File Extension",
    category: "File extension",
    pattern: "\\.[a-zA-Z0-9]{2,5}\\b",
    flags: "g",
    sampleText: "photo.jpg archive.zip script.ts",
  },
  {
    id: "india-mobile",
    title: "Indian Mobile",
    category: "Indian mobile number",
    pattern: "\\b[6-9]\\d{9}\\b",
    flags: "g",
    sampleText: "Contact 9876543210 or 8123456789",
  },
  {
    id: "india-pincode",
    title: "Indian Pincode",
    category: "Pincode",
    pattern: "\\b[1-9]\\d{5}\\b",
    flags: "g",
    sampleText: "Deliver to 110001 or 560001",
  },
];

export const exampleCategories = [
  ...new Set(regexExamples.map((e) => e.category)),
];
